on : [push]

jobs: 
 custom-composite-build:
 
  runs-on : ubuntu-latest
  
  name : Custom Composite Deploy Action

  steps:
    - name: Kubectl Control
      run: kubectl 
    - name : kubeconfig file 
      run : cat ~/.kube/config
  # steps:
  # - shell: bash
  #   env:
  #     SUPER_SECRET: ${{ secrets.SuperSecret }}