on : [push]

jobs: 
 custom-composite-build:
 
  runs-on : ubuntu-latest
  
  name : Custom Composite Build Action

  steps:
    - name : Build Action DevSecOpsCore 
      id : myjsaction
      uses: DevSecOpsCore/core-deploy@v1.0.0.1
      with:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
       

  # steps:
  # - shell: bash
  #   env:
  #     SUPER_SECRET: ${{ secrets.SuperSecret }}