on : [push]

jobs: 
 custom-composite-build:
 
  runs-on : ubuntu-latest
  
  name : Custom Composite Deploy Action

  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: ls -A files
      run : ls -A 
    - name : cat config
      run : cat config.txt

    - name: Kubectl Control
      run: kubectl 
    - name : kubeconfig file 
      run : ls -A /home/runner/
    - name: mkdir .kube directory
      run : mkdir /home/runner/.kube
    - name: .kube control
      run : ls -A /home/runner/
    
    - name : ls -A /home/runner/.kube/
      run : ls -A /home/runner/.kube/
    - name: cp config /home/runner/.kube/
      run : cp config.txt /home/runner/.kube/config
    - name : cat config
      run : cat /home/runner/.kube/config
    - name: kubectl control
      run : kubectl get nodes
    - name : echo secret
      run : echo ${{ secrets.QUAYIO_USERNAME }}
    - name : echo secret
      run : echo ${{ secrets.KUBECONFIG }}
  # steps:
  # - shell: bash
  #   env:
  #     SUPER_SECRET: ${{ secrets.SuperSecret }}