on : [push]

jobs: 
 custom-composite-build:
 
  runs-on : ubuntu-latest
  
  name : Custom Composite Deploy Action

  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: ls -A files
      run : ls -A 
   

    - name: Kubectl Control
      run: kubectl 
    - name : kubeconfig file 
      run : ls -A /home/runner/
    - name: mkdir .kube directory
      run : mkdir /home/runner/.kube
    - name: .kube control
      run : ls -A /home/runner/
    
    - name : ls -A /home/runner/.kube/
      run : ls -A /home/runner/.kube/

    - name : echo secret
      run :  cat <<< "${{ secrets.KUBECONFIG }}" > test.txt
    - name: exho test.txt
      run : cat test.txt 
    - name: cp test /home/runner/.kube/
      run : cp test.txt /home/runner/.kube/config 
    - name : cat config
      run : cat /home/runner/.kube/config
    - name: kubectl control
      run : kubectl get nodes
    - name : echo secret
      run : echo "${{ secrets.QUAYIO_USERNAME }}"
  # steps:
  # - shell: bash
  #   env:
  #     SUPER_SECRET: ${{ secrets.SuperSecret }}