on : [push]

jobs: 
 custom-composite-build:
 
  runs-on : ubuntu-latest
  
  name : Custom Composite Deploy Action

  steps:
    - name: ls -A files
      run : ls -A
    - name: Kubectl Control
      run: kubectl 
    - name : kubeconfig file 
      run : ls -A /home/runner/
    - name: mkdir .kube directory
      run : mkdir /home/runner/.kube
    - name: .kube control
      run : ls -A /home/runner/
    
    - name: touch /home/runner/.kube/config
      run : touch /home/runner/.kube/config
    - name : ls -A /home/runner/.kube/
      run : ls -A /home/runner/.kube/
   
  # steps:
  # - shell: bash
  #   env:
  #     SUPER_SECRET: ${{ secrets.SuperSecret }}