on : [push]

jobs: 
 custom-composite-build:
 
  runs-on : ubuntu-latest
  
  name : Custom Composite Deploy Action

  steps:
    - name: Kubectl Control
      run: kubectl 
    - name : kubeconfig file 
      run : ls -A /home/runner/
    - name: mkdir .kube directory
      run : mkdir /home/runner/.kube
    - name: .kube control
      run : ls -A /home/runner/
    
    - name: touch /home/runner/.kube/config
      run : touch /home/runner/.kube/config
    - name : ls -A /home/runner/.kube/
      run : ls -A /home/runner/.kube/
    - name: write config file data
      run : echo "this is a line" > /home/runner/.kube/config
    - name: cat config
      run: cat /home/runner/.kube/config
  # steps:
  # - shell: bash
  #   env:
  #     SUPER_SECRET: ${{ secrets.SuperSecret }}