name: Podman

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support 
# documentation.

on:
  push:
    branches: [ dev ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ master ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: quay.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: altug_yildirim/ubuntu-podman-runner
  IMAGE_TAG: v1


jobs:
  build:

    runs-on: [self-hosted,ocp-build]


    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Podman Login
        run: podman login quay.io -u altug_yildirim -p ${{ secrets.REPO_PASSWORD }}
        shell: bash
        
      - name: Podman Build
        run: podman build -t quay.io/altug_yildirim/java-demo:v1 -f /runner/_work/spring-boot-web-app/spring-boot-web-app/Dockerfile .
        shell: bash



      - name: Podman Push
        run: podman push quay.io/altug_yildirim/java-demo:v1
        shell: bash
      
