on : [push]

jobs: 
 custom-composite-build:
 
  runs-on : ubuntu-latest
  
  name : Custom Composite Build Action

  steps:
    - name : Podman login
      run: podman login quay.io -u ${{ secrets.QUAYIO_USERNAME }} -p ${{ secrets.QUAYIO_PASSWORD }}
    - name : Build Action DevSecOpsCore 
      id : myjsaction
      uses: DevSecOpsCore/core-build@v1.1.9
      with:
        jName : "devops-settings-example.json"  
    


  # steps:
  # - shell: bash
  #   env:
  #     SUPER_SECRET: ${{ secrets.SuperSecret }}