on : [push]

jobs: 
 custom-composite-build:
 
  runs-on : ubuntu-latest
  
  name : Custom Composite Build Action

  steps:
    - name : Build Action DevSecOpsCore 
      id : myjsaction
      uses: DevSecOpsCore/core-build@v2.0.5
      with:
        jName : "devops-settings-example.json"  
        RepoUserName: ${{ secrets.QUAYIO_USERNAME }}
        RepoPassword: ${{ secrets.QUAYIO_PASSWORD }}

  # steps:
  # - shell: bash
  #   env:
  #     SUPER_SECRET: ${{ secrets.SuperSecret }}