on : [push]

jobs: 
 custom-js-action-job:
 
  runs-on : ubuntu-latest
  
  name : Custom JS gitHub Action
  env:
    QUAYIO_USERNAME: swoturkey
  steps:
    - name : First GitHub Custom Action 
      id : myjsaction
      uses: enespekdas/ab-build@v2.1
      with:
        USERNAME : "${{env.QUAYIO_USERNAME}}"
        PASSWORD : "${{secrets.QUAYIO_PASSWD}}"  
    - name : env test
      run : echo "env test ediyorum ${{secrets.QUAYIO_PASSWD}}" 
    - name : Output of the TimeStamp
      run : echo "The time was ${{steps.myjsaction.outputs.time}}"
  


  # steps:
  # - shell: bash
  #   env:
  #     SUPER_SECRET: ${{ secrets.SuperSecret }}