on : [push]

jobs: 

 custom-composite-build:
 
  runs-on : ubuntu-latest
  
  name : Custom Composite Build Action

  steps:
  
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name : Build Action DevSecOpsCore 
      id : myjsaction
      uses: DevSecOpsCore/core-deploy@v1.0.1.3.2
      with:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
        dPath: "default"
        dName: "deployment.yaml"

