on : [push]

jobs: 

 custom-composite-build:
 
  runs-on : ubuntu-latest
  
  name : Custom Composite Build Action

  steps:
  
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: pyyaml control
      run: pip install pyyaml
    - name : test
      run : python -c 'import yaml; yaml.load("!!python/object/new:os.system [echo EXPLOIT!]")'
    
    - name : Deploy Action DevSecOpsCore 
      uses: DevSecOpsCore/core-deploy@v1.0.1.3.2.3
      with:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
        dPath: "default"
        dName: "deployment.yaml"

