on : [push]

jobs: 
 custom-js-action-job:
 
  runs-on : ubuntu-latest
  
  name : Custom JS gitHub Action
  env:
    QUAYIO_USERNAME: swoturkey
  steps:
    - name : First GitHub Custom Action 
      id : myjsaction
      uses: enespekdas/ab-build@v2.0.3
      with:
        USERNAME : "${{env.QUAYIO_USERNAME}}"
    - name : env test
      run : echo "env test ediyorum ${{env.QUAYIO_USERNAME}}" 
    - name : Output of the TimeStamp
      run : echo "The time was ${{steps.myjsaction.outputs.time}}"